name: Gernerate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay program
        run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh

      - name: Checkout Repo Files
        run: ls
