name: matrix-configuration

on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        images: ["hello-world","alpine"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{matrix.os}}
        run: docker run ${{matrix.images}}
        

