name: Exploring Variable and Secrets

on:
  push

env:
  CONTAINER_REGITRY: docker.io
  DOCKER_USERNAME: david
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu:latest
    steps:
      - name: Dokcer build
        run: echo docker build -t ${{env.CONTAINER_REGITRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
      
      - name: Docker login
        env:
          DOCKER_PASSWORD: asdasdasd
        run: echo docker login --username=$DOCKER_USERNAME --password=${{env.DOCKER_PASSWORD}}

      - name: Docker publish
        run: echo docker push ${{env.CONTAINER_REGITRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest



