name: Exploring Variable and Secrets

on:
  workflow_dispatch:
    
  # schedule:
  #   - cron: "*/1 * * * *"
#  push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Dokcer build
        run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

      - name: Docker login
        run: echo docker login --username=${{vars.DOCKER_USERNAME }} --password=${{secrets.DOCKER_PASSWORD}}

      - name: Docker publish
        run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    concurrency:
      group: production-docker
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Docker deploy
        timeout-minutes: 1
        run: |
          echo docker deploy ....
          sleep 600
      